(function(){(function(){var ma,y,M,na,oa,pa,qa,ba,D,ra,P,R,h;h=navigator.userAgent;h.match(/.+(?:me|ox|on|rv|it|era|opr|ie|OPR|IE)[\/: ]([\d.]+)/);/opera/i.test(h)||/opr/i.test(h);ma=/msie/i.test(h)&&!/opera/i.test(h)||/trident\//i.test(h);/msie 6/i.test(h)&&/opera/i.test(h);/msie 7/i.test(h)&&/opera/i.test(h);/msie 8/i.test(h)&&/opera/i.test(h);/msie 9/i.test(h)&&/opera/i.test(h);/msie 10/i.test(h)&&/opera/i.test(h);/firefox/i.test(h);/chrome/i.test(h)&&/opr/i.test(h);!/chrome/i.test(h)&&/webkit|safari|khtml/i.test(h);
/iemobile/i.test(h);/iphone|ipod|ipad/i.test(h);/opera mini|opera mobi/i.test(h);/opera mini/i.test(h);y=/windows/i.test(h);/linux/i.test(h);/mac/i.test(h);M=/iphone|ipod|ipad|opera mini|opera mobi|iemobile|android/i.test(h);/iphone/i.test(h);/ipod/i.test(h);/iphone.*OS 4/i.test(h);/ipod.*OS 4/i.test(h);/ipad/i.test(h);/android/i.test(h);/bada/i.test(h);if(y&&!M){null==window.console&&(window.console={debug:function(){},error:function(){},info:function(){},log:function(){}});if(null==window.mediamagnet_placeid)throw Error("mediamagnet_placeid is undefined");
D=["https://yadi.sk/d/","http://disk.yandex.ru/public/?hash=","https://disk.yandex.ru/public/?hash=","http://narod.ru/disk/"];ba=".zip .exe .rar .tar.gz .msi .torrent .7z .tgz .avi".split(" ");h=[];y=0;for(M=D.length;y<M;y++)R=D[y],h.push('a[href^="'+R+'"]');qa=[h].concat([function(){var a,b,c;c=[];a=0;for(b=ba.length;a<b;a++)R=ba[a],c.push('a[href$="'+R+'"]');return c}()]).join(", ");oa=function(a){return a.href};ra=function(a,b){return a.href=b};pa=function(a){return a.title||""};na=window.mediamagnet_manual||
function(a){var b,c,d,e,f,g,n,i,h,q,j,r;var ca=window.mediamagnet_links||qa;f="function"===typeof ca?ca:function(a){return a.Sizzle(ca)};d=window.mediamagnet_get_url||oa;g=window.mediamagnet_set_url||ra;var l=window.mediamagnet_label||pa;e="function"===typeof l?l:function(){return l};var s=window.mediamagnet_exe_name||"";c="function"===typeof s?s:function(){return s};var m=window.mediamagnet_zip||0;n="function"===typeof m?m:function(){return m};var k=window.mediamagnet_domain||"http://mediamagnet.cc";
b="function"===typeof k?k:function(){return k};j=f(a);r=[];h=0;for(q=j.length;h<q;h++)i=j[h],f=a.generateUrl(window.mediamagnet_placeid,e(i,a),d(i,a),c(i,a),b(i,a),n(i,a)),r.push(g(i,f,a));return r};P={base64encode:function(a){var b,c,d,e,f,g;b="";for(g=0;g<a.length;)c=a.charCodeAt(g++),d=a.charCodeAt(g++),e=a.charCodeAt(g++),f=c>>2,c=(c&3)<<4|d>>4,d=isNaN(d)?64:(d&15)<<2|e>>6,e=isNaN(e)?64:e&63,b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e);return b},base64decode:function(a){var b,c,d,e,f,g,n;b="";a=a.replace(/[^a-z0-9+/=]/gi,"");for(n=0;n<a.length;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),
g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(n++)),c=c<<2|d>>4,d=(d&15)<<4|f>>2,e=(f&3)<<6|g,b+=String.fromCharCode(c),64>f&&(b+=String.fromCharCode(d)),64>g&&(b+=String.fromCharCode(e));return b},generateUrl:function(a,b,c,d,e,f){c=ma?encodeURIComponent(P.base64encode(encodeURI(c))):encodeURIComponent(P.base64encode(c));c=""+e+"/download?id="+a+"&l="+encodeURIComponent(b)+"&u="+c+"&f="+encodeURIComponent(d);parseInt(f)&&(c+="&z="+f);return c}};D=function(a){P.Sizzle=
a();return na(P)};D.amd=!0}var S=window,l=function(a,b,c,d){var e,f,g,n,i;(b?b.ownerDocument||b:B)!==t&&H(b);b=b||t;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(n=b.nodeType)&&9!==n)return[];if(z&&!d){if(e=Ca.exec(a))if(g=e[1])if(9===n)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&Q(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return E.apply(c,b.getElementsByTagName(a)),c;if((g=e[3])&&
k.getElementsByClassName&&b.getElementsByClassName)return E.apply(c,b.getElementsByClassName(g)),c}if(k.qsa&&(!u||!u.test(a))){f=e=p;g=b;i=9===n&&a;if(1===n&&"object"!==b.nodeName.toLowerCase()){n=T(a);(e=b.getAttribute("id"))?f=e.replace(Da,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=n.length;g--;)n[g]=f+U(n[g]);g=da.test(a)&&b.parentNode||b;i=n.join(",")}if(i)try{return E.apply(c,g.querySelectorAll(i)),c}catch(h){}finally{e||b.removeAttribute("id")}}}var q;a:{a=a.replace(V,"$1");f=T(a);
if(!d&&1===f.length){e=f[0]=f[0].slice(0);if(2<e.length&&"ID"===(q=e[0]).type&&k.getById&&9===b.nodeType&&z&&j.relative[e[1].type]){b=(j.find.ID(q.matches[0].replace(F,G),b)||[])[0];if(!b){q=c;break a}a=a.slice(e.shift().value.length)}for(n=W.needsContext.test(a)?0:e.length;n--;){q=e[n];if(j.relative[g=q.type])break;if(g=j.find[g])if(d=g(q.matches[0].replace(F,G),da.test(e[0].type)&&b.parentNode||b)){e.splice(n,1);a=d.length&&U(e);if(!a){E.apply(c,d);q=c;break a}break}}}ea(a,f)(d,b,!z,c,da.test(a));
q=c}return q},v=function(){function a(c,d){b.push(c+=" ")>j.cacheLength&&delete a[b.shift()];return a[c]=d}var b=[];return a},w=function(a){a[p]=!0;return a},x=function(a){var b=t.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}};y=function(a,b){for(var c=a.split("|"),d=a.length;d--;)j.attrHandle[c[d]]=b};var ta=function(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||sa)-(~a.sourceIndex||sa);if(d)return d;if(c)for(;c=
c.nextSibling;)if(c===b)return-1;return a?1:-1};M=function(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}};h=function(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}};var I=function(a){return w(function(b){b=+b;return w(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)if(c[e=f[g]])c[e]=!(d[e]=c[e])})})},ua=function(){},T=function(a,b){var c,d,e,f,g,n,i;if(g=va[a+" "])return b?0:g.slice(0);g=a;n=[];for(i=j.preFilter;g;){if(!c||
(d=Ea.exec(g)))d&&(g=g.slice(d[0].length)||g),n.push(e=[]);c=!1;if(d=Fa.exec(g))c=d.shift(),e.push({value:c,type:d[0].replace(V," ")}),g=g.slice(c.length);for(f in j.filter)if((d=W[f].exec(g))&&(!i[f]||(d=i[f](d))))c=d.shift(),e.push({value:c,type:f,matches:d}),g=g.slice(c.length);if(!c)break}return b?g.length:g?l.error(a):va(a,n).slice(0)},U=function(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d},fa=function(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=Ga++;return b.first?function(c,
b,f){for(;c=c[d];)if(1===c.nodeType||e)return a(c,b,f)}:function(c,b,i){var h,q,j,r=C+" "+f;if(i)for(;c=c[d];){if((1===c.nodeType||e)&&a(c,b,i))return!0}else for(;c=c[d];)if(1===c.nodeType||e)if(j=c[p]||(c[p]={}),(q=j[d])&&q[0]===r){if(!0===(h=q[1])||h===X)return!0===h}else if(q=j[d]=[r],q[1]=a(c,b,i)||X,!0===q[1])return!0}},ga=function(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]},Y=function(a,b,c,d,e){for(var f,g=[],n=0,i=a.length,h=null!=
b;n<i;n++)if(f=a[n])if(!c||c(f,d,e))g.push(f),h&&b.push(n);return g},ha=function(a,b,c,d,e,f){d&&!d[p]&&(d=ha(d));e&&!e[p]&&(e=ha(e,f));return w(function(g,f,i,h){var q,j,r=[],k=[],p=f.length,s;if(!(s=g)){s=b||"*";for(var m=i.nodeType?[i]:i,t=[],u=0,v=m.length;u<v;u++)l(s,m[u],t);s=t}s=a&&(g||!b)?Y(s,r,a,i,h):s;m=c?e||(g?a:p||d)?[]:f:s;c&&c(s,m,i,h);if(d){q=Y(m,k);d(q,[],i,h);for(i=q.length;i--;)if(j=q[i])m[k[i]]=!(s[k[i]]=j)}if(g){if(e||a){if(e){q=[];for(i=m.length;i--;)if(j=m[i])q.push(s[i]=j);
e(null,m=[],q,h)}for(i=m.length;i--;)if((j=m[i])&&-1<(q=e?J.call(g,j):r[i]))g[q]=!(f[q]=j)}}else m=Y(m===f?m.splice(p,m.length):m),e?e(null,f,m,h):E.apply(f,m)})},ia=function(a){var b,c,d,e=a.length,f=j.relative[a[0].type];c=f||j.relative[" "];for(var g=f?1:0,h=fa(function(a){return a===b},c,!0),i=fa(function(a){return-1<J.call(b,a)},c,!0),k=[function(a,c,d){return!f&&(d||c!==Z)||((b=c).nodeType?h(a,c,d):i(a,c,d))}];g<e;g++)if(c=j.relative[a[g].type])k=[fa(ga(k),c)];else{c=j.filter[a[g].type].apply(null,
a[g].matches);if(c[p]){for(d=++g;d<e&&!j.relative[a[d].type];d++);return ha(1<g&&ga(k),1<g&&U(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(V,"$1"),c,g<d&&ia(a.slice(g,d)),d<e&&ia(a=a.slice(d)),d<e&&U(a))}k.push(c)}return ga(k)},N,k,X,j,$,wa,ea,Z,K,H,t,A,z,u,L,aa,Q,p="sizzle"+-new Date,B=S.document,C=0,Ga=0,xa=v(),va=v(),ya=v(),O=!1,ja=function(a,b){a===b&&(O=!0);return 0},sa=-2147483648,Ha={}.hasOwnProperty,v=[],Ia=v.pop,Ja=v.push,E=v.push,za=v.slice,J=v.indexOf||function(a){for(var b=
0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},Aa="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),Ba="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+Aa+")|)|)[\\x20\\t\\r\\n\\f]*\\]",ka=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+Ba.replace(3,8)+")*)|.*)\\)|)",V=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$",
"g"),Ea=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Fa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,da=/[\x20\t\r\n\f]*[+~]/,Ka=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*)[\\x20\\t\\r\\n\\f]*\\]","g"),La=RegExp(ka),Ma=RegExp("^"+Aa+"$"),W={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Ba),PSEUDO:RegExp("^"+ka),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},la=/^[^{]+\{\s*\[native \w/,Ca=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,Na=/^(?:input|select|textarea|button)$/i,Oa=/^h\d$/i,Da=/'|\\/g,F=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)",
"ig"),G=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{E.apply(v=za.call(B.childNodes),B.childNodes),v[B.childNodes.length].nodeType}catch(Pa){E={apply:v.length?function(a,b){Ja.apply(a,za.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}wa=l.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};k=l.support={};H=l.setDocument=function(a){var b=a?
a.ownerDocument||a:B,a=b.defaultView;if(b===t||9!==b.nodeType||!b.documentElement)return t;t=b;A=b.documentElement;z=!wa(b);a&&(a.attachEvent&&a!==a.top)&&a.attachEvent("onbeforeunload",function(){H()});k.attributes=x(function(a){a.className="i";return!a.getAttribute("className")});k.getElementsByTagName=x(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});k.getElementsByClassName=x(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className=
"i";return 2===a.getElementsByClassName("i").length});k.getById=x(function(a){A.appendChild(a).id=p;return!b.getElementsByName||!b.getElementsByName(p).length});k.getById?(j.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&z){var e=b.getElementById(a);return e&&e.parentNode?[e]:[]}},j.filter.ID=function(a){var b=a.replace(F,G);return function(a){return a.getAttribute("id")===b}}):(delete j.find.ID,j.filter.ID=function(a){var b=a.replace(F,G);return function(a){return(a="undefined"!==
typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}});j.find.TAG=k.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var e,f=[],g=0,h=b.getElementsByTagName(a);if("*"===a){for(;e=h[g++];)1===e.nodeType&&f.push(e);return f}return h};j.find.CLASS=k.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&z)return b.getElementsByClassName(a)};L=[];u=[];if(k.qsa=la.test(b.querySelectorAll))x(function(a){a.innerHTML=
"<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||u.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||u.push(":checked")}),x(function(a){var d=b.createElement("input");d.setAttribute("type","hidden");a.appendChild(d).setAttribute("t","");a.querySelectorAll("[t^='']").length&&u.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");
a.querySelectorAll(":enabled").length||u.push(":enabled",":disabled");a.querySelectorAll("*,:x");u.push(",.*:")});(k.matchesSelector=la.test(aa=A.webkitMatchesSelector||A.mozMatchesSelector||A.oMatchesSelector||A.msMatchesSelector))&&x(function(a){k.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");L.push("!=",ka)});u=u.length&&RegExp(u.join("|"));L=L.length&&RegExp(L.join("|"));Q=la.test(A.contains)||A.compareDocumentPosition?function(a,b){var e=9===a.nodeType?a.documentElement:a,f=b&&b.parentNode;
return a===f||!(!f||!(1===f.nodeType&&(e.contains?e.contains(f):a.compareDocumentPosition&&a.compareDocumentPosition(f)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ja=A.compareDocumentPosition?function(a,d){if(a===d)return O=!0,0;var e=d.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(d);return e?e&1||!k.sortDetached&&d.compareDocumentPosition(a)===e?a===b||Q(B,a)?-1:d===b||Q(B,d)?1:K?J.call(K,a)-J.call(K,d):0:e&4?-1:1:a.compareDocumentPosition?
-1:1}:function(a,d){var e,f=0;e=a.parentNode;var g=d.parentNode,h=[a],i=[d];if(a===d)return O=!0,0;if(!e||!g)return a===b?-1:d===b?1:e?-1:g?1:K?J.call(K,a)-J.call(K,d):0;if(e===g)return ta(a,d);for(e=a;e=e.parentNode;)h.unshift(e);for(e=d;e=e.parentNode;)i.unshift(e);for(;h[f]===i[f];)f++;return f?ta(h[f],i[f]):h[f]===B?-1:i[f]===B?1:0};return b};l.matches=function(a,b){return l(a,null,null,b)};l.matchesSelector=function(a,b){(a.ownerDocument||a)!==t&&H(a);b=b.replace(Ka,"='$1']");if(k.matchesSelector&&
z&&(!L||!L.test(b))&&(!u||!u.test(b)))try{var c=aa.call(a,b);if(c||k.disconnectedMatch||a.document&&11!==a.document.nodeType)return c}catch(d){}return 0<l(b,t,null,[a]).length};l.contains=function(a,b){(a.ownerDocument||a)!==t&&H(a);return Q(a,b)};l.attr=function(a,b){(a.ownerDocument||a)!==t&&H(a);var c=j.attrHandle[b.toLowerCase()],c=c&&Ha.call(j.attrHandle,b.toLowerCase())?c(a,b,!z):void 0;return void 0===c?k.attributes||!z?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null:
c};l.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};l.uniqueSort=function(a){var b,c=[],d=0,e=0;O=!k.detectDuplicates;K=!k.sortStable&&a.slice(0);a.sort(ja);if(O){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}return a};$=l.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=$(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=
a[d];d++)c+=$(b);return c};j=l.selectors={cacheLength:50,createPseudo:w,match:W,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(F,G);a[3]=(a[4]||a[5]||"").replace(F,G);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||l.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||
"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&l.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(W.CHILD.test(a[0]))return null;if(a[3]&&void 0!==a[4])a[2]=a[4];else if(c&&La.test(c)&&(b=T(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(F,G).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=xa[a+
" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&xa(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")})},ATTR:function(a,b,c){return function(d){d=l.attr(d,a);if(null==d)return"!="===b;if(!b)return!0;d+="";return"="===b?d===c:"!="===b?d!==c:"^="===b?c&&0===d.indexOf(c):"*="===b?c&&-1<d.indexOf(c):"$="===b?c&&d.slice(-c.length)===c:"~="===b?-1<(" "+d+" ").indexOf(c):"|="===b?d===
c||d.slice(0,c.length+1)===c+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,j){var k,r,l,t,s,c=f!==g?"nextSibling":"previousSibling",m=b.parentNode,u=h&&b.nodeName.toLowerCase(),j=!j&&!h;if(m){if(f){for(;c;){for(r=b;r=r[c];)if(h?r.nodeName.toLowerCase()===u:1===r.nodeType)return!1;s=c="only"===a&&!s&&"nextSibling"}return!0}s=[g?m.firstChild:m.lastChild];if(g&&j){j=m[p]||(m[p]={});
k=j[a]||[];t=k[0]===C&&k[1];l=k[0]===C&&k[2];for(r=t&&m.childNodes[t];r=++t&&r&&r[c]||(l=t=0)||s.pop();)if(1===r.nodeType&&++l&&r===b){j[a]=[C,t,l];break}}else if(j&&(k=(b[p]||(b[p]={}))[a])&&k[0]===C)l=k[1];else for(;r=++t&&r&&r[c]||(l=t=0)||s.pop();)if((h?r.nodeName.toLowerCase()===u:1===r.nodeType)&&++l)if(j&&((r[p]||(r[p]={}))[a]=[C,l]),r===b)break;l-=e;return l===d||0===l%d&&0<=l/d}}},PSEUDO:function(a,b){var c,d=j.pseudos[a]||j.setFilters[a.toLowerCase()]||l.error("unsupported pseudo: "+a);
return d[p]?d(b):1<d.length?(c=[a,a,"",b],j.setFilters.hasOwnProperty(a.toLowerCase())?w(function(a,c){for(var g,h=d(a,b),i=h.length;i--;)g=J.call(a,h[i]),a[g]=!(c[g]=h[i])}):function(a){return d(a,0,c)}):d}},pseudos:{not:w(function(a){var b=[],c=[],d=ea(a.replace(V,"$1"));return d[p]?w(function(a,b,c,h){for(var h=d(a,null,h,[]),i=a.length;i--;)if(c=h[i])a[i]=!(b[i]=c)}):function(a,f,g){b[0]=a;d(b,null,g,c);return!c.pop()}}),has:w(function(a){return function(b){return 0<l(a,b).length}}),contains:w(function(a){return function(b){return-1<
(b.textContent||b.innerText||$(b)).indexOf(a)}}),lang:w(function(a){Ma.test(a||"")||l.error("unsupported lang: "+a);a=a.replace(F,G).toLowerCase();return function(b){var c;do if(c=z?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(a){var b=S.location&&S.location.hash;return b&&b.slice(1)===a.id},root:function(a){return a===A},focus:function(a){return a===t.activeElement&&
(!t.hasFocus||t.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;return!0},parent:function(a){return!j.pseudos.empty(a)},
header:function(a){return Oa.test(a.nodeName)},input:function(a){return Na.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:I(function(){return[0]}),last:I(function(a,b){return[b-1]}),eq:I(function(a,b,c){return[0>c?c+b:c]}),even:I(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),
odd:I(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:I(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:I(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};j.pseudos.nth=j.pseudos.eq;for(N in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})j.pseudos[N]=M(N);for(N in{submit:!0,reset:!0})j.pseudos[N]=h(N);ua.prototype=j.filters=j.pseudos;j.setFilters=new ua;ea=l.compile=function(a,b){var c,d=[],e=[],f=ya[a+" "];if(!f){b||(b=T(a));for(c=b.length;c--;)f=ia(b[c]),
f[p]?d.push(f):e.push(f);var g=0,h=0<d.length,i=0<e.length;c=function(a,b,c,f,k){var p,s,m=[],u=0,v="0",w=a&&[],x=null!=k,y=Z,z=a||i&&j.find.TAG("*",k&&b.parentNode||b),A=C+=null==y?1:Math.random()||0.1,B=z.length;x&&(Z=b!==t&&b,X=g);for(;v!==B&&null!=(p=z[v]);v++){if(i&&p){for(k=0;s=e[k++];)if(s(p,b,c)){f.push(p);break}x&&(C=A,X=++g)}h&&((p=!s&&p)&&u--,a&&w.push(p))}u+=v;if(h&&v!==u){for(k=0;s=d[k++];)s(w,m,b,c);if(a){if(0<u)for(;v--;)!w[v]&&!m[v]&&(m[v]=Ia.call(f));m=Y(m)}E.apply(f,m);x&&(!a&&0<
m.length&&1<u+d.length)&&l.uniqueSort(f)}x&&(C=A,Z=y);return w};c=h?w(c):c;f=ya(a,c)}return f};k.sortStable=p.split("").sort(ja).join("")===p;k.detectDuplicates=O;H();k.sortDetached=x(function(a){return a.compareDocumentPosition(t.createElement("div"))&1});x(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||y("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!k.attributes||!x(function(a){a.innerHTML="<input/>";
a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&y("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});x(function(a){return null==a.getAttribute("disabled")})||y("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return(d=a.getAttributeNode(b))&&d.specified?d.value:!0===a[b]?b.toLowerCase():null});"function"===typeof D&&
D.amd?D(function(){return l}):S.Sizzle=l}).call(this);}).call(this);
